
chunksize: 25000
queue: "standard"
conda-env: True
scaleout: 200
retries: 50               # Retries for fault tolerance
mem-per-worker: 8         # More memory per worker

# Custom setup commands for condor jobs
custom-setup-commands:
  - "source /cvmfs/cms.cern.ch/cmsset_default.sh"
  - "export USER_CXXFLAGS='-Wno-misleading-indentation'"
  - "export MAMBA_ROOT_PREFIX=/data/dust/user/leyvaped/ttHbb_software/micromamba"
#  - "eval \"$(/data/dust/user/leyvaped/ttHbb_software/micromamba_bin/micromamba shell hook -s bash -p /data/dust/user/leyvaped/ttHbb_software/micromamba)\""
  - "micromamba activate pocket-coffea"

# chunksize means the number of events that will be processed by each worker
# scaleout means the number of workers that will be used (or jobs running in parallel)
# queue means the queue to use
# mem-per-worker means the memory per worker
# see more in https://pocketcoffea.readthedocs.io/en/latest/running.html



